import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { GlobalProvider } from "./context/globalContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <script
          src="https://kit.fontawesome.com/069bdcd509.js"
          crossOrigin="anonymous"
        ></script>
      </head>
      <GlobalProvider>
        <body className={inter.className}>{children}</body>
      </GlobalProvider>
    </html>
  );
}
